services:
  db:
    image: postgres:16
    container_name: ddi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build:
      context: .
      dockerfile: src/data-pipelines/Dockerfile
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ddi
      PGSCHEMA: public
    volumes:
      - ./data:/app/data       
    working_dir: /app

volumes:
  pgdata:
