name: Terraform Cleanup

jobs:
    terraform-cleanup:
        name: Terraform Cleanup
        runs-on: Ubuntu-latest

        env: "us-east-2"
        TF_VERSION: "1.13.4"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: "Install Terraform"
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: "Configure AWS credentials"
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: "Terraform Init"
              working-directory: terraform
              run: terraform init

            - name: "Terraform Cleanup"
              working-directory: terraform
              run: terraform destroy -auto-approve
