name: Terraform Cleanup

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    terraform-cleanup:
        name: Terraform Cleanup
        runs-on: ubuntu-latest

        env:
            AWS_REGION: "us-east-2"
            TF_VERSION: "1.13.4"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: "Install Terraform"
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: "Configure AWS credentials"
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  role-session-name: ${{ github.run_id }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: "Terraform Init"
              working-directory: terraform
              run: terraform init

            - name: "Terraform Cleanup"
              working-directory: terraform
              run: terraform destroy -auto-approve
